name:                parser-basic
version:             0.1.0.0
github:              "Michaelt293/parser-basic"
license:             BSD3
author:              "Michael Thomas"
maintainer:          "Michaelt293@gmail.com"
copyright:           "2018 Michael Thomas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Michaelt293/parser-basic#readme>

dependencies:
- base >= 4.7 && < 5
- bifunctors

library:
  source-dirs: src

executables:
  parser-basic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parser-basic

tests:
  parser-basic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parser-basic
